
name: Publish to Codecov

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt install graphviz
        python -m pip install --upgrade pip
        pip install coverage
    - name: Run coverage tests
      run: coverage xml
    - name: Publish results to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}